### ISSUE TITLE
You will be falsely DMCA'd

### ISSUE THREAD

**Issue by EternityX** [ALittlePatate/millionware-v3#2]
Post this to a site that does not follow DMCA laws.

**Comment by codecheck01** [comment]
We have copies and it will be published on offshore leak forums. (no DMCA)

**Comment by ALittlePatate** [comment]
Don't worry, i made plenty of copies + a lot of people downloaded the source already, striking it now would have 0 effect.

**Comment by EternityX** [comment]
> We have copies and it will be published on offshore leak forums. (no DMCA)



> Don't worry, i made plenty of copies + a lot of people downloaded the source already, striking it now would have 0 effect.

Good work guys, thanks 👍
